import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useKeyboard } from "./hooks/useKeyboard";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

// CJK Unified Ideographs + common fullwidth punctuation
const CJK_RE = /[一-鿿㐀-䶿＀-￯]/g;

/**
 * Estimate spoken duration from narration text. Detects CJK vs Latin
 * and picks the matching pace:
 *   Chinese ≈ 4 char/s (250 ms/char)
 *   English ≈ 150 wpm  (400 ms/word)
 * Mixed text blends both proportionally.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  const cjkChars = (text.match(CJK_RE) || []).length;
  const latinPart = text.replace(CJK_RE, " ").trim();
  const latinWords = latinPart ? latinPart.split(/\s+/).length : 0;
  const ms = cjkChars * 250 + latinWords * 400;
  return Math.max(1500, ms);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  useKeyboard({
    stepper,
    mode,
    autoStarted,
    cycleMode,
    setAutoStarted,
    chapters: CHAPTERS,
  });

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
